spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 748540242994-d6478k55hkkae82r5tkvac7igs68q9sa.apps.googleusercontent.com
  datasource:
    url: jdbc:derby:codebreaker_db;create=true;collation=TERRITORY_BASED:PRIMARY
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: ddl.sql

server:
  port: 18081
  servlet:
    context-path: /codebreaker